# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cabinet.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cabinet(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1164, 638)
        Dialog.setMinimumSize(QtCore.QSize(1164, 0))
        Dialog.setMaximumSize(QtCore.QSize(1164, 16777215))
        Dialog.setStyleSheet("background-color:#0f1021;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-4, -8, 1171, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:#d01257;color:#ffcee4;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(20, 580, 151, 31))
        self.pushButton.setStyleSheet("color:#ffcee4;border:none;border-radius:10px;background-color:#d01257;")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 120, 1171, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#d01257;color:#ffcee4;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 210, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:none;color:#ffcee4;")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(10, 240, 331, 31))
        self.lineEdit.setStyleSheet("color:#ffcee4;border:2px solid #d01257;border-radius:10px;")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 240, 151, 31))
        self.pushButton_2.setStyleSheet("color:#ffcee4;border:none;border-radius:10px;background-color:#d01257;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 310, 331, 31))
        self.lineEdit_2.setStyleSheet("color:#ffcee4;border:2px solid #d01257;border-radius:10px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 310, 151, 31))
        self.pushButton_3.setStyleSheet("color:#ffcee4;border:none;border-radius:10px;background-color:#d01257;")
        self.pushButton_3.setObjectName("pushButton_3")

        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(1000, 580, 151, 31))
        self.pushButton_4.setStyleSheet("color:#ffcee4;border:none;border-radius:10px;background-color:#d01257;")
        self.pushButton_4.setObjectName("pushButton_3")

        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 280, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:none;color:#ffcee4;")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_3.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.lineEdit.raise_()
        self.pushButton_2.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_3.raise_()
        self.label_4.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "kino"))
        self.label.setText(_translate("Dialog", "Личный кабинет"))
        self.pushButton.setText(_translate("Dialog", "Удалить аккаунт"))
        self.label_2.setText(_translate("Dialog", "ФИО:\n"
"Дата рождения:"))
        self.label_3.setText(_translate("Dialog", "Логин"))
        self.pushButton_2.setText(_translate("Dialog", "Сменить"))
        self.pushButton_3.setText(_translate("Dialog", "Сменить"))
        self.pushButton_4.setText(_translate("Dialog", "Выйти из аккаунта"))
        self.label_4.setText(_translate("Dialog", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
