# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'places.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class PlacesUi_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1164, 638)
        Dialog.setMinimumSize(QtCore.QSize(1164, 0))
        Dialog.setMaximumSize(QtCore.QSize(1164, 16777215))
        Dialog.setStyleSheet("background-color:#0f1021;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(-4, -8, 1171, 91))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:#d01257;color:#ffcee4;")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.b1 = QtWidgets.QPushButton(Dialog)
        self.b1.setGeometry(QtCore.QRect(340, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b1.setFont(font)
        self.b1.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b1.setObjectName("b1")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(0, 90, 1161, 101))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setText("")
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.b2 = QtWidgets.QPushButton(Dialog)
        self.b2.setGeometry(QtCore.QRect(390, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b2.setFont(font)
        self.b2.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(Dialog)
        self.b3.setGeometry(QtCore.QRect(440, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b3.setFont(font)
        self.b3.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(Dialog)
        self.b4.setGeometry(QtCore.QRect(490, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b4.setFont(font)
        self.b4.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b4.setObjectName("b4")
        self.b5 = QtWidgets.QPushButton(Dialog)
        self.b5.setGeometry(QtCore.QRect(540, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b5.setFont(font)
        self.b5.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b5.setObjectName("b5")
        self.b6 = QtWidgets.QPushButton(Dialog)
        self.b6.setGeometry(QtCore.QRect(590, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b6.setFont(font)
        self.b6.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b6.setObjectName("b6")
        self.b7 = QtWidgets.QPushButton(Dialog)
        self.b7.setGeometry(QtCore.QRect(640, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b7.setFont(font)
        self.b7.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b7.setObjectName("b7")
        self.b8 = QtWidgets.QPushButton(Dialog)
        self.b8.setGeometry(QtCore.QRect(690, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b8.setFont(font)
        self.b8.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b8.setObjectName("b8")
        self.b9 = QtWidgets.QPushButton(Dialog)
        self.b9.setGeometry(QtCore.QRect(740, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b9.setFont(font)
        self.b9.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b9.setObjectName("b9")
        self.b10 = QtWidgets.QPushButton(Dialog)
        self.b10.setGeometry(QtCore.QRect(790, 310, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b10.setFont(font)
        self.b10.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b10.setObjectName("b10")
        self.b18 = QtWidgets.QPushButton(Dialog)
        self.b18.setGeometry(QtCore.QRect(690, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b18.setFont(font)
        self.b18.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b18.setObjectName("b18")
        self.b20 = QtWidgets.QPushButton(Dialog)
        self.b20.setGeometry(QtCore.QRect(790, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b20.setFont(font)
        self.b20.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b20.setObjectName("b20")
        self.b17 = QtWidgets.QPushButton(Dialog)
        self.b17.setGeometry(QtCore.QRect(640, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b17.setFont(font)
        self.b17.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b17.setObjectName("b17")
        self.b16 = QtWidgets.QPushButton(Dialog)
        self.b16.setGeometry(QtCore.QRect(590, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b16.setFont(font)
        self.b16.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b16.setObjectName("b16")
        self.b12 = QtWidgets.QPushButton(Dialog)
        self.b12.setGeometry(QtCore.QRect(390, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b12.setFont(font)
        self.b12.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b12.setObjectName("b12")
        self.b13 = QtWidgets.QPushButton(Dialog)
        self.b13.setGeometry(QtCore.QRect(440, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b13.setFont(font)
        self.b13.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b13.setObjectName("b13")
        self.b19 = QtWidgets.QPushButton(Dialog)
        self.b19.setGeometry(QtCore.QRect(740, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b19.setFont(font)
        self.b19.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b19.setObjectName("b19")
        self.b11 = QtWidgets.QPushButton(Dialog)
        self.b11.setGeometry(QtCore.QRect(340, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b11.setFont(font)
        self.b11.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b11.setObjectName("b11")
        self.b14 = QtWidgets.QPushButton(Dialog)
        self.b14.setGeometry(QtCore.QRect(490, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b14.setFont(font)
        self.b14.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b14.setObjectName("b14")
        self.b15 = QtWidgets.QPushButton(Dialog)
        self.b15.setGeometry(QtCore.QRect(540, 380, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b15.setFont(font)
        self.b15.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b15.setObjectName("b15")
        self.b27 = QtWidgets.QPushButton(Dialog)
        self.b27.setGeometry(QtCore.QRect(690, 450, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b27.setFont(font)
        self.b27.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b27.setObjectName("b27")
        self.b26 = QtWidgets.QPushButton(Dialog)
        self.b26.setGeometry(QtCore.QRect(640, 450, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b26.setFont(font)
        self.b26.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b26.setObjectName("b26")
        self.b25 = QtWidgets.QPushButton(Dialog)
        self.b25.setGeometry(QtCore.QRect(590, 450, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b25.setFont(font)
        self.b25.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b25.setObjectName("b25")
        self.b21 = QtWidgets.QPushButton(Dialog)
        self.b21.setGeometry(QtCore.QRect(390, 450, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b21.setFont(font)
        self.b21.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b21.setObjectName("b21")
        self.b22 = QtWidgets.QPushButton(Dialog)
        self.b22.setGeometry(QtCore.QRect(440, 450, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b22.setFont(font)
        self.b22.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b22.setObjectName("b22")
        self.b28 = QtWidgets.QPushButton(Dialog)
        self.b28.setGeometry(QtCore.QRect(740, 450, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b28.setFont(font)
        self.b28.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b28.setObjectName("b28")
        self.b23 = QtWidgets.QPushButton(Dialog)
        self.b23.setGeometry(QtCore.QRect(490, 450, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b23.setFont(font)
        self.b23.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b23.setObjectName("b23")
        self.b24 = QtWidgets.QPushButton(Dialog)
        self.b24.setGeometry(QtCore.QRect(540, 450, 41, 51))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(11)
        self.b24.setFont(font)
        self.b24.setStyleSheet("border:none;background-color:#b0d1b9;\n"
"border-bottom-left-radius: 15px;border-bottom-right-radius: 15px;\n"
"border-top-left-radius: 5px;border-top-right-radius: 5px;")
        self.b24.setObjectName("b24")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("kino", "kino"))
        self.b1.setText(_translate("Dialog", "1"))
        self.b2.setText(_translate("Dialog", "2"))
        self.b3.setText(_translate("Dialog", "3"))
        self.b4.setText(_translate("Dialog", "4"))
        self.b5.setText(_translate("Dialog", "5"))
        self.b6.setText(_translate("Dialog", "6"))
        self.b7.setText(_translate("Dialog", "7"))
        self.b8.setText(_translate("Dialog", "8"))
        self.b9.setText(_translate("Dialog", "9"))
        self.b10.setText(_translate("Dialog", "10"))
        self.b18.setText(_translate("Dialog", "18"))
        self.b20.setText(_translate("Dialog", "20"))
        self.b17.setText(_translate("Dialog", "17"))
        self.b16.setText(_translate("Dialog", "16"))
        self.b12.setText(_translate("Dialog", "12"))
        self.b13.setText(_translate("Dialog", "13"))
        self.b19.setText(_translate("Dialog", "19"))
        self.b11.setText(_translate("Dialog", "11"))
        self.b14.setText(_translate("Dialog", "14"))
        self.b15.setText(_translate("Dialog", "15"))
        self.b27.setText(_translate("Dialog", "27"))
        self.b26.setText(_translate("Dialog", "26"))
        self.b25.setText(_translate("Dialog", "25"))
        self.b21.setText(_translate("Dialog", "21"))
        self.b22.setText(_translate("Dialog", "22"))
        self.b28.setText(_translate("Dialog", "28"))
        self.b23.setText(_translate("Dialog", "23"))
        self.b24.setText(_translate("Dialog", "24"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
